
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFile System/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
/**
 *
 * @author AZRIEL
 */
public class PenjualanMotor extends javax.swing.JFrame {
    int matic,sepeda,diskon,total,harga,totaldiskon;
    

    /**
     * Creates new form PenjualanMotor
     */
    public PenjualanMotor() {     
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbo_merk = new javax.swing.JComboBox<>();
        rd_matic = new javax.swing.JRadioButton();
        txt_harga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbo_pembayaran = new javax.swing.JComboBox<>();
        btn_hitung = new javax.swing.JButton();
        rd_sepeda = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_diskon = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        btn_hitunglagi = new javax.swing.JButton();
        btn_selesai = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JIEL'S MOTOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 330, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("NAMA PEMBELI");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 80, 100, 16);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));
        jPanel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("DATA MOTOR");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("MERK MOTOR");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("JENIS");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("HARGA");

        cbo_merk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH", "GESITS", "VOLTA", "OYIKA", "ECGO 2" }));
        cbo_merk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbo_merkFocusGained(evt);
            }
        });
        cbo_merk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_merkActionPerformed(evt);
            }
        });

        btn_group1.add(rd_matic);
        rd_matic.setText("MATIC");
        rd_matic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rd_maticFocusGained(evt);
            }
        });
        rd_matic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_maticActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("PEMBAYARAN");

        cbo_pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH", "TUNAI", "KREDIT" }));
        cbo_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_pembayaranActionPerformed(evt);
            }
        });

        btn_hitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hitung.setText("HITUNG");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        btn_group1.add(rd_sepeda);
        rd_sepeda.setText("SEPEDA LISTRIK");
        rd_sepeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_sepedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hitung))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cbo_merk, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rd_matic)
                                        .addGap(18, 18, 18)
                                        .addComponent(rd_sepeda))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbo_merk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rd_matic)
                    .addComponent(rd_sepeda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_harga, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbo_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_hitung)))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 110, 400, 200);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("HARGA MOTOR");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("DISKON");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("TOTAL BAYAR");

        txt_diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diskonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(70, 310, 400, 119);
        getContentPane().add(txt_nama);
        txt_nama.setBounds(170, 70, 165, 30);

        btn_hitunglagi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hitunglagi.setText("HITUNG LAGI");
        btn_hitunglagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitunglagiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hitunglagi);
        btn_hitunglagi.setBounds(110, 440, 110, 23);

        btn_selesai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_selesai.setText("SELESAI");
        btn_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selesaiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_selesai);
        btn_selesai.setBounds(300, 440, 80, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Documents\\NetBeansProjects\\JavaApplication1\\3.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 60, 580, 550);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 560, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hitunglagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitunglagiActionPerformed
        // TODO add your handling code here:
        txt_diskon.setText("");
        txt_harga.setText("");
        txt_nama.setText("");
        txt_total.setText("");
        cbo_merk.setSelectedItem("PILIH");
        cbo_pembayaran.setSelectedItem("PILIH");
        btn_group1.clearSelection();
                
    }//GEN-LAST:event_btn_hitunglagiActionPerformed

    private void btn_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selesaiActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(null, "lololo yakin mau keluar?","Konfirmasi keluar aplikasi",JOptionPane.OK_OPTION);
        if (konfirmasi == JOptionPane.OK_OPTION)
        {
            dispose();
        }
     
    }//GEN-LAST:event_btn_selesaiActionPerformed

    private void cbo_merkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_merkActionPerformed
        // TODO add your handling code here:
        if(cbo_merk.getSelectedItem().equals("GESITS"))
        {
            matic = 28000000;
            sepeda = 9975000;
    } else
    if(cbo_merk.getSelectedItem().equals("VOLTA"))
    {
            matic = 15700000;
            sepeda = 4800000;
    } else
      
    if(cbo_merk.getSelectedItem().equals("OYIKA"))
    {
            matic = 17000000;
            sepeda = 4100000;
    } else
        if(cbo_merk.getSelectedItem().equals("ECGO 2"))
    {
            matic = 13000000;
            sepeda = 5540000;
    }//GEN-LAST:event_cbo_merkActionPerformed
    }
    private void cbo_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_pembayaranActionPerformed
        // TODO add your handling code here:
        if(cbo_merk.getSelectedItem().equals("GESITS"))
        {
            if(cbo_pembayaran.getSelectedItem().equals ("TUNAI"))
                diskon = 20;
                txt_diskon.setText(String.valueOf(diskon));
        }
        else
            if(cbo_pembayaran.getSelectedItem().equals("KREDIT"))
            {
                diskon = 8;
                txt_diskon.setText(String.valueOf(diskon));
            }    
         if(cbo_merk.getSelectedItem().equals("VOLTA"))
        {
            if(cbo_pembayaran.getSelectedItem().equals ("TUNAI"))
                diskon = 20;
                txt_diskon.setText(String.valueOf(diskon));
        }
        else
            if(cbo_pembayaran.getSelectedItem().equals("KREDIT"))
            {
                diskon = 7;
                txt_diskon.setText(String.valueOf(diskon));
            }  
         if(cbo_merk.getSelectedItem().equals("OYIKA"))
        {
            if(cbo_pembayaran.getSelectedItem().equals ("TUNAI"))
                diskon = 20;
                txt_diskon.setText(String.valueOf(diskon));
        }
        else
            if(cbo_pembayaran.getSelectedItem().equals("KREDIT"))
            {
                diskon = 6;
                txt_diskon.setText(String.valueOf(diskon));
            }  
         if(cbo_merk.getSelectedItem().equals("ECGO 2"))
        {
            if(cbo_pembayaran.getSelectedItem().equals ("TUNAI"))
                diskon = 20;
                txt_diskon.setText(String.valueOf(diskon));
        }
        else
            if(cbo_pembayaran.getSelectedItem().equals("KREDIT"))
            {
                diskon = 5;
                txt_diskon.setText(String.valueOf(diskon));
            }  
         
         
    }//GEN-LAST:event_cbo_pembayaranActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        harga = Integer.parseInt(txt_harga.getText());
        diskon = Integer.parseInt(txt_diskon.getText());
        totaldiskon = (diskon * harga)/100;
        total = harga - totaldiskon;
        txt_diskon.setText(String.valueOf(totaldiskon));
        txt_total.setText(String.valueOf(total));
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void rd_maticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_maticActionPerformed
        // TODO add your handling code here:
        if(rd_matic.isSelected())
        {
            txt_harga.setText(String.valueOf(matic));
        }
    }//GEN-LAST:event_rd_maticActionPerformed

    private void cbo_merkFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbo_merkFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_merkFocusGained

    private void rd_maticFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rd_maticFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_maticFocusGained

    private void rd_sepedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_sepedaActionPerformed
if(rd_sepeda.isSelected())
        {
            txt_harga.setText(String.valueOf(sepeda));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_rd_sepedaActionPerformed

    private void txt_diskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diskonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenjualanMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenjualanMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenjualanMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenjualanMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenjualanMotor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_group1;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_hitunglagi;
    private javax.swing.JButton btn_selesai;
    private javax.swing.JComboBox<String> cbo_merk;
    private javax.swing.JComboBox<String> cbo_pembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rd_matic;
    private javax.swing.JRadioButton rd_sepeda;
    private javax.swing.JTextField txt_diskon;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
